version: "3.8"

services:
    mailserver:
        image: mailserver/docker-mailserver:11.2.0
        mem_limit: 4G
        mem_reservation: 2G
        restart: on-failure:40
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "5m"
        hostname: mail
        domainname: ${DOMAIN_NAME}
        dns: ${DNS_SERVER:-1.1.1.1}
        stop_grace_period: 1m
        networks:
            mail_infra_network:
                aliases:
                    - mail-server.${DOMAIN_NAME}
                    - imap.${DOMAIN_NAME}
                    - smtp.${DOMAIN_NAME}
                    - ldap.${DOMAIN_NAME}
                    - pop.${DOMAIN_NAME}
        ports:
            - "25:25"    # SMTP  (explicit TLS => STARTTLS)
            - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
            - "465:465"  # ESMTP (implicit TLS)
            - "587:587"  # ESMTP (explicit TLS => STARTTLS)
            - "993:993"  # IMAP4 (implicit TLS)
            - "110:110"  # POP3
            - "995:995"  # POP3 (with TLS)
            - "4190:4190" # Sieve filters
            - "4177:4177" # Dovecot replication
        volumes:
            - ${MAIL_DATA_DIR}:/var/mail
            - ${MAIL_STATE_DIR}:/var/mail-state
            - ${MAIL_LOGS_DIR}:/var/log/mail
            - ${MAIL_CONFIGS_DIR}:/tmp/docker-mailserver/
            - ${USER_PATCHES_FILE:-./user-patches.sh}:/tmp/docker-mailserver/user-patches.sh:ro
            - ${ACME_HOME_DIR}/${DOMAIN_NAME}-mirror3:/acme.sh/${DOMAIN_NAME}/
            - ./cron/sa-learn:/etc/cron.d/sa-learn:ro
            - ${SASLAUTHD_SOCKET_FILE}:/var/run/saslauthd/mux
        environment:
            TZ: UTC
            OVERRIDE_HOSTNAME: ${OVERRIDE_HOSTNAME}
            ENABLE_SPAMASSASSIN: "1"
            ENABLE_SPAMASSASSIN_KAM: "1"
            SPAMASSASSIN_SPAM_TO_INBOX: "1"
            ENABLE_CLAMAV: "1"
            ENABLE_AMAVIS: "1"
            ENABLE_FAIL2BAN: "1"
            ENABLE_POSTGREY: "1"
            ENABLE_POP3: "1"
            ENABLE_MANAGESIEVE: "1"
            ENABLE_SASLAUTHD: "0" # The docker container manages it
            ONE_DIR: "1"
            LOG_LEVEL: "${LOG_LEVEL:-warn}"
            ACCOUNT_PROVISIONER: "LDAP"
            POSTGREY_DELAY: "${POSTGREY_DELAY:-300}"
            LDAP_SERVER_HOST: "ldaps://ldap.${DOMAIN_NAME}" # Must match the hostname for SSL verification
            DOVECOT_URIS: "ldaps://ldap.${DOMAIN_NAME}" # Must match the hostname for SSL verification
            LDAP_SEARCH_BASE: "ou=people,${LDAP_BASE_DN}"
            LDAP_BIND_DN: "cn=admin,${LDAP_BASE_DN}"
            LDAP_BIND_PW: ${LDAP_ADMIN_PASSWORD}
            LDAP_QUERY_FILTER_USER: "(&(mail=%s)(mailEnabled=TRUE))"
            LDAP_QUERY_FILTER_GROUP: "(&(mailGroupMember=%s)(mailEnabled=TRUE))"
            LDAP_QUERY_FILTER_ALIAS: "(|(&(mailAlias=%s)(objectClass=PostfixBookMailAccount))(&(mailAlias=%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE)))"
            LDAP_QUERY_FILTER_DOMAIN: "(|(&(mail=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailGroupMember=*@%s)(objectClass=PostfixBookMailAccount)(mailEnabled=TRUE))(&(mailalias=*@%s)(objectClass=PostfixBookMailAccount)))"
            DOVECOT_PASS_FILTER: "(&(objectClass=PostfixBookMailAccount)(mail=%n@%d))"
            DOVECOT_USER_FILTER: "(&(objectClass=PostfixBookMailAccount)(mail=%n@%d))"
            DOVECOT_DEFAULT_PASS_SCHEME: "SSHA256"
            TLS_LEVEL: "intermediate"
            POSTFIX_MESSAGE_SIZE_LIMIT: "100000000"
            DOVECOT_TLS_CACERT_FILE: "/acme.sh/${DOMAIN_NAME}/ca.cer"
            DOVECOT_TLS_VERIFY_CLIENT: "try"
            DOVECOT_ADM_PASS: "${DOVECOT_ADM_PASS}"
            DOVECOT_REPLICA_SERVER: "${DOVECOT_REPLICA_SERVER}"
            SSL_TYPE: "manual"
            SSL_CERT_PATH: "/acme.sh/${DOMAIN_NAME}/fullchain.cer"
            SSL_KEY_PATH: "/acme.sh/${DOMAIN_NAME}/${DOMAIN_NAME}.key"
            # Daily report & reporting
            POSTMASTER_ADDRESS: "${POSTMASTER_ADDRESS}"
            VIRUS_ADMIN_EMAIL: "${VIRUS_ADMIN_EMAIL}"
            VIRUS_X_HEADER_LINE: "${VIRUS_X_HEADER_LINE}"
            PFLOGSUMM_RECIPIENT: "${PFLOGSUMM_RECIPIENT}"
            PFLOGSUMM_TRIGGER: daily_cron
            LOGWATCH_INTERVAL: daily
            LOGWATCH_RECIPIENT: "${LOGWATCH_RECIPIENT}"
            # Fail2ban config to allow IPs to make failed attempts
            FAIL2BAN_IGNORE_IPS: "${FAIL2BAN_IGNORE_IPS}"
            FAIL2BAN_DST_EMAIL: "${FAIL2BAN_DST_EMAIL}"
            FAIL2BAN_SENDER_EMAIL: "${FAIL2BAN_SENDER_EMAIL}"
            FAIL2BAN_SENDER_NAME: "${FAIL2BAN_SENDER_NAME}"
        healthcheck:
            test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
            timeout: 3s
            retries: 0
        depends_on:
            - openldap
            - acme
        cap_add:
            - NET_ADMIN # fail2ban
            #- CAP_CHOWN # supervisor uses sockchown
        security_opt:
          - no-new-privileges:true
        #cap_drop:
        #    - ALL

    openldap:
        image: botsudo/docker-openldap
        restart: on-failure:5
        mem_limit: 1G
        mem_reservation: 100M
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "1m"
        hostname: ldap.${DOMAIN_NAME}
        domainname: ldap.${DOMAIN_NAME}
        healthcheck:
            test: 'ldapwhoami -D "cn=$${DOCKER_LDAP_HEALTHCHECK_USERNAME}" -w "$${DOCKER_LDAP_HEALTHCHECK_PASSWORD}"'
            start_period: 5s
            interval: 30s
            timeout: 5s
            retries: 3
        networks:
            mail_infra_network:
                aliases:
                    - ldap.${DOMAIN_NAME}
        environment:
            # 256 to enable debug
            # See: https://www.openldap.org/doc/admin24/slapdconf2.html
            LDAP_LOG_LEVEL: ${LDAP_LOG_LEVEL:-0}
            LDAP_OPENLDAP_GID: 0
            LDAP_OPENLDAP_UID: 0
            LDAP_TLS_CRT_FILENAME: "/container/service/slapd/assets/certs/server.cer"
            LDAP_TLS_KEY_FILENAME: "/container/service/slapd/assets/certs/server.key"
            LDAP_TLS_CA_CRT_FILENAME: "/container/service/slapd/assets/certs/ca.cer"
            LDAP_TLS_CIPHER_SUITE: "HIGH:MEDIUM:-SSLv2"
            # never | allow | try | demand
            LDAP_TLS_VERIFY_CLIENT: "try"
            LDAP_BASE_DN: "${LDAP_BASE_DN}"
            LDAP_AUTH_BASE_DN: "ou=people,${LDAP_BASE_DN}"
            LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
            LDAP_CONFIG_PASSWORD: ${LDAP_CONFIG_PASSWORD}
            LDAP_MONITOR_PASSWORD: ${LDAP_MONITOR_PASSWORD}
            # Only used by healthcheck command defined above
            DOCKER_LDAP_HEALTHCHECK_USERNAME: ${DOCKER_LDAP_HEALTHCHECK_USERNAME}
            DOCKER_LDAP_HEALTHCHECK_PASSWORD: ${DOCKER_LDAP_HEALTHCHECK_PASSWORD}
            # Add ldaps:/// to SSL listen
            LDAP_LISTEN_URLS: "ldap:/// ldapi:/// ldaps:///"
        volumes:
            - ${LDAP_DATA_DIR}:/var/lib/openldap/openldap-data
            - ${ACME_HOME_DIR}/${DOMAIN_NAME}/ca.cer:/container/service/slapd/assets/certs/ca.cer:ro
            - ${ACME_HOME_DIR}/${DOMAIN_NAME}/fullchain.cer:/container/service/slapd/assets/certs/server.cer:ro
            - ${ACME_HOME_DIR}/${DOMAIN_NAME}/${DOMAIN_NAME}.key:/container/service/slapd/assets/certs/server.key:ro
            - ${SASLAUTHD_SOCKET_FILE}:/var/run/saslauthd/mux
        ports:
            - "${LDAP_PORT:-389}:389"
            - "${LDAPS_PORT:-636}:636"
        depends_on:
            acme:
                condition: service_healthy
        security_opt:
          - no-new-privileges:true

    phpldapadmin:
        image: osixia/phpldapadmin:latest
        mem_limit: 512M
        mem_reservation: 100M
        restart: on-failure:5
        logging:
            driver: "json-file"
            options:
                max-file: "1"
                max-size: "200k"
        networks:
            mail_infra_network:
                aliases:
                    - ldap-admin.${DOMAIN_NAME}
        healthcheck:
            test: 'php -r ''$$c = is_string(file_get_contents("https://localhost?ping=pong", false, stream_context_create(["ssl" => ["verify_peer"=> false, "verify_peer_name"=> true, "peer_name"=> "${DOMAIN_NAME}", "peer_fingerprint" => openssl_x509_fingerprint(file_get_contents("/container/service/phpldapadmin/assets/apache2/certs/fullchain.cer")) ]]))); echo $$c; exit($$c === true ? 0 : 1);'''
            start_period: 15s
            interval: 30s
            timeout: 3s
            retries: 3
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap.${DOMAIN_NAME}': [{'server': [{'tls': True}]},{'login': [{'bind_id': 'cn=admin,${LDAP_BASE_DN}'}]}]}]"
            PHPLDAPADMIN_HTTPS_CRT_FILENAME: "fullchain.cer"
            PHPLDAPADMIN_HTTPS_KEY_FILENAME: "${DOMAIN_NAME}.key"
            PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: "ca.cer"
            PHPLDAPADMIN_LDAP_CLIENT_TLS_CA_CRT_FILENAME: "ca.cer"
        volumes:
            - ${ACME_HOME_DIR}/${DOMAIN_NAME}-mirror1:/container/service/phpldapadmin/assets/apache2/certs
            - ${ACME_HOME_DIR}/${DOMAIN_NAME}-mirror1:/container/service/ldap-client/assets/certs
        ports:
            - "${PHPLDAPADMIN_SSL_PORT:-8080}:443"
        depends_on:
            openldap:
                condition: service_healthy
            acme:
                condition: service_healthy
        security_opt:
          - no-new-privileges:true
    acme:
        image: neilpang/acme.sh:latest
        mem_limit: 512M
        mem_reservation: 10M
        restart: on-failure:15
        logging:
            driver: "json-file"
            options:
                max-file: "2"
                max-size: "200k"
        volumes:
            - ./scripts:/scripts:ro
            - ${ACME_HOME_DIR}:/acme.sh
        working_dir: /scripts/
        healthcheck:
            test: ["CMD", "sh", "/scripts/healthcheck.sh"]
            start_period: 10s
            interval: 30s
            timeout: 2s
            retries: 30
        environment:
            # CloudFlare
            CF_Key: ${CF_API_KEY}
            CF_Email: ${CF_API_EMAIL}
            DOMAIN_NAME: ${DOMAIN_NAME}
            DOMAIN_NAMES: "${DOMAIN_NAMES}"
            DNS_API: "dns_cf"
            ACME_SH_EMAIL: "${ACME_SH_EMAIL:-}"
            ACME_SH_EAB_KID: "${ACME_SH_EAB_KID:-}"
            ACME_SH_EAB_HMAC: "${ACME_SH_EAB_HMAC:-}"
            ACME_COMMAND_ARGUMENTS: ${ACME_COMMAND_ARGUMENTS:-}
            ACME_ISSUE_ARGUMENTS: ${ACME_ISSUE_ARGUMENTS:-}
        entrypoint: /bin/sh
        command: /scripts/acme.sh-docker.sh
        security_opt:
          - no-new-privileges:true
networks:
    mail_infra_network:
        driver: bridge
        name: infrastructure_mail_infra_network
