name: run full tests
on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: run shellcheck
              uses: sudo-bot/action-shellcheck@latest
              with:
                  cli-args: "--format=checkstyle --severity=info --enable=all scripts/*.sh"
    run-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: copy the test env
              run: cp tests/.env.test1 .env
            - name: docker-compose build
              run: docker-compose build
            - name: docker-compose up
              run: docker-compose up -d
            - name: Sleep some time
              run: sleep 10
            - name: Build phpunit test suite
              run: docker-compose -f tests/php/docker-compose.yml build
            - name: Run phpunit test suite
              run: docker-compose -f tests/php/docker-compose.yml up --build
            - name: docker-compose stop
              run: docker-compose stop
            - name: docker-compose logs
              run: docker-compose logs
            - name: docker-compose down
              run: docker-compose down

