name: run full tests
on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: run shellcheck
              uses: sudo-bot/action-shellcheck@latest
              with:
                  cli-args: "--format=checkstyle --severity=info --enable=all scripts/*.sh"
    run-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: copy the test env
              run: cp tests/.env.test1 .env
            - name: docker-compose build
              uses: sudo-bot/action-docker-compose@latest
              with:
                  # https://docs.docker.com/compose/reference/overview/
                  cli-args: "build"
            - name: docker-compose up
              uses: sudo-bot/action-docker-compose@latest
              with:
                  # https://docs.docker.com/compose/reference/overview/
                  cli-args: "up -d"
            - name: Sleep some time
              run: sleep 10
            - name: docker-compose stop
              uses: sudo-bot/action-docker-compose@latest
              with:
                  # https://docs.docker.com/compose/reference/overview/
                  cli-args: "stop"
            - name: docker-compose logs
              uses: sudo-bot/action-docker-compose@latest
              with:
                  # https://docs.docker.com/compose/reference/overview/
                  cli-args: "logs"
            - name: docker-compose down
              uses: sudo-bot/action-docker-compose@latest
              with:
                  # https://docs.docker.com/compose/reference/overview/
                  cli-args: "down"

