name: run full tests
on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: run shellcheck
              uses: sudo-bot/action-shellcheck@latest
              with:
                  cli-args: "--format=checkstyle --severity=info --enable=all scripts/*.sh"
    run-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup for tests
              run: make setup
            - name: run tests
              run: make test
            - name: teardown tests
              run: make teardown
