name: run full tests
on: [push]

permissions:
    contents: read
    packages: read

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: run shellcheck
              uses: sudo-bot/action-shellcheck@latest
              with:
                  cli-args: "--format=checkstyle --severity=info --enable=all scripts/*.sh"
    run-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Docker compose version
              run: docker compose version
            - name: Login to GitHub registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: create temp folder
              run: make create-temp-env
            - name: setup for tests
              run: make setup-test
            - name: run docker-test
              run: make run-test
              env:
                  IMAGE_TAG: ghcr.io/datacenters-network/mails/mailserver
            - name: teardown tests
              run: make cleanup-test
